### ISSUE TITLE
Add prestop script support to deployment container

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/sbt-kubeyml#130]
Example:
```yaml
lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "echo "Bye" ]
```
