### ISSUE TITLE
Add support for config map

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/sbt-kubeyml#209]
In deployment:
```yaml
envFrom:
            - configMapRef:
                name: <service name>
```

Config map ref name should also be configurable
