### ISSUE TITLE
Add hostAliases support in Deployment plugin

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/sbt-kubeyml#50]
Goes in the template spec
```
hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
```
which is equivalent to the pod spec
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
